# Generated by Django 4.0.4 on 2022-04-18 23:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_programminglanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.IntegerField(choices=[('1', 'Male'), ('2', 'Female')])),
            ],
            managers=[
                ('employees', django.db.models.manager.Manager()),
            ],
        ),
    ]
